### ISSUE TITLE
There should be an option to re-enable other CoreGui elements when you disable the top bar

### ISSUE THREAD

**Issue by boynedmaster** [Roblox/Core-Scripts#1023]
Right now, if you disable the top bar with :SetCore("TopbarEnabled", false) it will not only disable the top bar but also all other CoreGui elements. This is frustrating because it forces developers who want to make a custom top bar to also have to reimplement things like chat, the player list, the backpack, etc. This is especially unnecessary when we already have SetCoreGuiEnabled.

Chat in specific is an annoying one, and if TopbarEnabled didn't get rid of the chat a developer could possibly just run ToggleVisibility/SetVisible from CoreGuiChatConnections or ChatActive. 

Although I wish this was how it worked when it was first introduced, but making a change like this be the default would of course cause backwards incompatibilities. I propose adding a SetCore option of something along the lines of "DisablingTopbarDisablesOthers". It's an awful name, but I can't come up with anything better. The default value would have the same behavior as TopbarEnabled currently does, but the opposite value should just get rid of the buttons for chat and backpack, but not their functionality.

**Comment by boynedmaster** [comment]
I'm going to try and implement this, I just need someone to come up with a good name.

**Comment by VRService** [comment]
imho This is a feature, not a bug - it isn't something for the community to make a PR for

**Comment by boynedmaster** [comment]
You mean to suggest that a developer wouldn't want an easy option to keep the default chat to make a custom topbar? 

Closing not because of your comment but because feature requests aren't allowed by the community.

**Comment by VRService** [comment]
I'm sure they would - but this is why the devforums exist

**Comment by boynedmaster** [comment]
A lot of developers, including me, aren't allowed into the dev forum and don't get responses back on applications. With the S&I forums gone (and likely not even read much anyway) there aren't many ways to suggest things.

Also, just realized the meaning of your original comment in that feature requests don't go into Issues, not that the chat and other elements being removed with the top bar is a feature, unless that's actually what you mean.

**Comment by VRService** [comment]
Yeah - I meant that this isn't the place to ask for features for stuff that ROBLOX knows exists / is an issue
Just ask someone on the devforum to request this - in fact, I'll do it now

**Comment by boynedmaster** [comment]
Yeah, I got you. Thanks for requesting, I'm not personal with anybody at the dev forums.

**Comment by VRService** [comment]
https://devforum.roblox.com/t/api-for-keeping-coregui-enabled-with-setcore/49468
