### ISSUE TITLE
Chat bar dissapears

### ISSUE THREAD

**Issue by penguin0616** [Roblox/Core-Scripts#1030]
![image](https://user-images.githubusercontent.com/23770056/29490711-a3d1a3f6-8509-11e7-86af-44b4ebeeb638.png)

I joined a server, and my chat bar was just missing. I could still talk though.
This has happened to me twice, both in a different game.
The picture provided is of the error from the developer console.

**Comment by VRService** [comment]
Are you, or is the game maker, using a custom chat / any additional chat functionality?

**Comment by iLordPenguin** [comment]
Nope.
