### ISSUE TITLE
[RFC] Diceroll Chat Command

### ISSUE THREAD

**Issue by stillunt1tled** [Roblox/Core-Scripts#1039]
How about a */roll* chat command for roleplaying? (since we already have the /me command).

**Syntax**: /roll [number (defaults to 100 if ommited)]
**Output in chat**: *[player] rolled a [random number] out of [number].*

**Example**: *stillunt1tled rolled a 49 out of 100.*

**Comment by VRService** [comment]
That should be for the Developer Forums Feature Requests, not here

**Comment by stillunt1tled** [comment]
I personally don't have a devforum account
