### ISSUE TITLE
Chat Signals are only lowercase methods, which is out of standard with Roblox's implementations

### ISSUE THREAD

**Issue by Quenty** [Roblox/Core-Scripts#1043]
https://github.com/Roblox/Core-Scripts/blob/899ad4877fb2e953b5251f2061a50c1f223d8629/CoreScriptsRoot/Modules/ChatUtil.lua#L17

Unlike Roblox signals, where `connect` is depreciated, and `Connect` is preferred, the ChatUtil only implements lowercase `:connect()`

**Comment by boynedmaster** [comment]
Same with :wait() and :Wait().

**Comment by stillunt1tled** [comment]
I'm assuming this is also true with :fire()?

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.
