### ISSUE TITLE
In the new player list, entries not sorting correctly

### ISSUE THREAD

**Issue by jmargh** [ROBLOX/Core-Scripts#105]
Currently only sorting by player name, not by the primary leader stat.

**Comment by einsteinK** [comment]
If an issue is self-assigned, does it mean others (like me) can make a pull request to fix it?

**Comment by jmargh** [comment]
I'm trying to start using the issue tracker on github to file bugs that are reported through the developer forums or that we see in game, on the official forums, etc. to better document things and so the issues don't get lost.

For this issue, I've already started work on it.
