### ISSUE TITLE
Why do I get this warning?

### ISSUE THREAD

**Issue by tattoosfour** [Roblox/Core-Scripts#1063]
I'm programming a script for running xbox gamepad for pc, I get the following warning and the game does not work well, does not move the character and selects the name of the player.

02:05:57.630 - GuiService:AddSelectionParent already has selection group with name PlayerlistGuiSelection, overwriting selection group. (x55)

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.
