### ISSUE TITLE
Invisicam does not have smooth zooming

### ISSUE THREAD

**Issue by Quenty** [Roblox/Core-Scripts#1064]
Invisicam does not have smooth zooming

**Comment by LoganDark** [comment]
What do you mean?

**Comment by SwimyGreen** [comment]
In November-ish, Roblox released an update that smooths out the animation when you zoom your camera with the scroll wheel. But for whatever reason it's not working or not implemented for invisicam, making zooming choppier.

Until today, my game was using invisicam on a fork of the camera script from a year ago, and after updating it behaves exactly the same as previously.

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.
