### ISSUE TITLE
How to change Backpack HotKey?

### ISSUE THREAD

**Issue by KovarMachane** [Roblox/Core-Scripts#1065]
On some international keyboards, the top left key ( ` ) or ( ~ ) does not work to open the default Roblox backpack. It happens in the Windows Roblox application.
Roblox is aware, but have not fixed it: This snipet of the Backpack CoreScript speaks for itself:

_local ARROW_HOTKEY = Enum.KeyCode.Backquote.Value **--TODO: Hookup '~' too?**
local ARROW_HOTKEY_STRING = '`'_

How can a developer assign a different hot key to open core Backpack?
Or, at least, is there a way to know if the Backpack is open or not?

Thanks for any ideas!

**Comment by LoganDark** [comment]
https://github.com/Roblox/Core-Scripts/blob/425d2d641bdc4b6c1104a9d5f6c53c9ea758c5cb/CoreScriptsRoot/Modules/BackpackScript.lua#L1808-L1809

https://github.com/Roblox/Core-Scripts/blob/425d2d641bdc4b6c1104a9d5f6c53c9ea758c5cb/CoreScriptsRoot/Modules/BackpackScript.lua#L1812

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.

**Comment by LoganDark** [comment]
The dev forum is hostile towards new users and not a very good bug tracker in general.

By assuming every open issue on this repository is irrelevant and forcing people to make posts on the devforum if they "feel it is still relevant", you are basically ignoring every issue where the author (or someone else) does not feel the need to make a new post on the forum.

Some issue migration strategy (where some existing issues are migrated to the forum, at least) would be smart; but this is not.

**Comment by cliffchapmanrbx** [comment]
I'm sorry I don't have a better option for you. This repository has been out of date for over 2 years and unmaintained for nearly 4, and based on the number of spam comments I've had to delete just to be able to safely close out these tickets we have little interest in reviving this repository. The DevForum is the place our client development team monitors and listens to feedback, this repository is not monitored by anyone.
