### ISSUE TITLE
|Technical Suggestion & Issue| Roblox still uses DirectInput For Keyboard Recognition.

### ISSUE THREAD

**Issue by ComparedArray** [Roblox/Core-Scripts#1068]
There is a small problem. Roblox uses DirectInput, An unreliable Library in which only Game Controllers ran run off of. If you do not know what I'm talking about : https://docs.microsoft.com/en-us/windows/win32/xinput/xinput-and-directinput

At the same time, I recommend, If you are going to update roblox Further, you do not use the "Shell" Of the Kernel's Input Recognition Software. In the future of Windows, This will become a problem as you should rather use Windows Key Regs. I'll try to update on better docs later. https://msdn.microsoft.com/en-us/windows/ee418998(v=vs.80) This shows some of the Limitations as of: "Because DirectInput works directly with the device drivers, it either suppresses or ignores Windows mouse and keyboard messages. It also ignores mouse and keyboard settings made by the user in Control Panel." - Documentation. I'm just telling you this because in the future of Windows, DirectInput will be Archived, and Most key combinations will NOT be registered by windows. Direct input does allow you to use Calibration sets, But I do recommend that you use both. The DirectInput from DirectX Will support Controllers, Ect. Whilst using Windows keydb Events which will allow you to log all Pre-Registered keys, And their Events.

Thank you,
-<Array_Simplified>

Contact me at:
<Coding_Simplified>#9040

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.
