### ISSUE TITLE
New player list won't hide

### ISSUE THREAD

**Issue by SSonic70** [ROBLOX/Core-Scripts#108]
I am unable to hide the new player list using the SetCoreGuiEnabled method in StarterGui.

Reproduction steps:
1. Open Studio with a new place.
2. Insert a local script into StarterGui with the following code:
```lua
game.StarterGui:SetCoreGuiEnabled("PlayerList",false)
```
3. Play solo or use test servers. The player list doesn't hide.

**Comment by jmargh** [comment]
Was able to reproduce in play solo but not start server->start player. Looks to be a race condition between when a script sets it to false and when the core script connects the event. Will put a fix in later today.
