### ISSUE TITLE
PromptPurchase: Able to buy model that you already own

### ISSUE THREAD

**Issue by Usering** [ROBLOX/Core-Scripts#110]
If you prompt purchase a free model and you already own it, you are able to take it again. It doesn't do anything, but the behavior is just weird.

Example:
![screen shot 2015-02-01 at 1 21 33 am](https://cloud.githubusercontent.com/assets/6396337/5991637/fc4b7c1e-a9b0-11e4-9891-4626065b315b.png)
![screen shot 2015-02-01 at 1 21 38 am](https://cloud.githubusercontent.com/assets/6396337/5991638/fc6b27ee-a9b0-11e4-9bd2-7ba876e109cc.png)

**Comment by jmargh** [comment]
This should be handled now with the new purchase prompt script. Did a quick test, was able to take a free model, then upon trying to take it again it prompted me that I owned the item, and is only showing the OK button. If you could confirm it's good behavior with the new purchase script that would be awesome. If not I'll look into it. Thanks!
