### ISSUE TITLE
 MarketplaceService:getProductInfo() failed because mc

### ISSUE THREAD

**Issue by TheSneak** [ROBLOX/Core-Scripts#129]
This error occurs from time to time on line 89 of LoadingScript

`coroutine.resume(coroutine.create(function() GameAssetInfo = MPS:GetProductInfo(PLACEID) end))`

The following errors also occurs at the same place: 

`MarketplaceService:getProductInfo() failed because HTTP -1200`
`MarketplaceService:getProductInfo() failed because HTTP 404 (HTTP/1.1 302 Found) `
`MarketplaceService:getProductInfo() failed because https://api.roblox.com/marketplace/productinfo?assetId=<PlaceID>: HttpSendRequest, err=0x2EFF`

**Comment by jmargh** [comment]
Are the additional errors happening from your own script?

**Comment by TheSneak** [comment]
No. All errors originate at line 89 of LoadingScript.
