### ISSUE TITLE
Using disabled API

### ISSUE THREAD

**Issue by einsteinK** [ROBLOX/Core-Scripts#149]
http://api.roblox.com/users/{userId}/canmanage/{assetId}

The FFlag UseCanManageApiToDetermineConsoleAccess got enabled very recently.
The new API that the FFlag forces the client to use, however, is still enabled.
F9 serverside console won't load for anyone. (Not even game creator)

I also heard of an issue of a place's stats page not loading, could be related to this.

**Comment by jmargh** [comment]
I have passed this along to the person who enabled that flag and he'll be looking into it. I will close this once he addresses this issue. Thanks!

**Comment by dignatoff** [comment]
The web api should be enabled now, please reply here or to the dev forum thread http://developer.roblox.com/forum/client-bug-reports/14651-developer-console-busted-on-name-change#157899 if you continue to have issues.

**Comment by jmargh** [comment]
Closing issue.
