### ISSUE TITLE
User created GUIs on Topbar

### ISSUE THREAD

**Issue by AlexwareRBLX** [ROBLOX/Core-Scripts#150]
I want to be able to put other GUIs on the topbar, such as user created GUI buttons to open up GUIs, but the top bar is in the way of clicking them. Please fix

**Comment by Only20** [comment]
The Topbar is not intended to host custom GUIs at this time.

**Comment by kyle-emmerich** [comment]
That's stupid. It's because it's poorly coded, and that's not a good excuse.
