### ISSUE TITLE
Unable to expand the leaderboard

### ISSUE THREAD

**Issue by Gskartwii** [ROBLOX/Core-Scripts#151]
You used to be able to expand the leaderboard by pressing the TAB key, but with the new Core GUI, you can't. (According to SchnitzelSandwich)

**Comment by jmargh** [comment]
The expand was removed from the top bar version of the player list.

**Comment by Gskartwii** [comment]
That is why I opened this issue. Oh well.

**Comment by jmargh** [comment]
This is more of a request than an issue. It is not a bug, we changed the behavior of the player list with the top bar version.
