### ISSUE TITLE
Improper way to detect device type

### ISSUE THREAD

**Issue by Phalanxia** [ROBLOX/Core-Scripts#152]
https://github.com/ROBLOX/Core-Scripts/blob/master/CoreScriptsRoot/CoreScripts/Topbar.lua#L969-L982

Using the screen resolution this way is not the proper way of detecting device type. For example, many phones would be detected as "Desktop" by this function. Example: The iPhone 6 Plus has a screen resolution of "1920 x 1080".

Also, this code does nothing. Why's it in full release?

**Comment by SolarCrane** [comment]
The iPhone 6 Plus has a native screen resolution of 1920 x 1080, but Roblox does not render at full native resolution for phones and tablet devices. While the code does not change the state of the program it was left in there as a [Method Stub](http://en.wikipedia.org/wiki/Method_stub) for testing and future development.

**Comment by kyle-emmerich** [comment]
How in the world did you get hired by ROBLOX?

**Comment by Sorcus** [comment]
SolarCrane is operated purely on solar energy and this is something we highly value here at ROBLOX. So an offer was immediately given. Please let me know if you have any further questions.

**Comment by kyle-emmerich** [comment]
Alright, if Sorcus says it's so, it's so.

**Comment by Phalanxia** [comment]
:sun_with_face:

**Comment by Sorcus** [comment]
For product related questions you are more than welcome to contact me directly. You know where to find me. Let's end this discussion here as this probably bothers others who are subscribed to this issue.
