### ISSUE TITLE
Newlines at end of files.

### ISSUE THREAD

**Issue by Phalanxia** [ROBLOX/Core-Scripts#154]
Always have one newline at the end of each lua script file. Many here have anywhere between [zero](https://github.com/ROBLOX/Core-Scripts/blob/master/CoreScriptsRoot/CoreScripts/ChatScript2.lua#L2100) and [nine](https://github.com/ROBLOX/Core-Scripts/blob/master/CoreScriptsRoot/CoreScripts/Topbar.lua#L1097-L1105). Please keep things consistent and clean! I know it may seem like a small thing, but it isn't.

Sources:
* https://robots.thoughtbot.com/no-newline-at-end-of-file
* https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file
* https://coderwall.com/p/icxxna/don-t-forget-that-extra-line

**Comment by Only20** [comment]
This is a stylistic concern and not a bug.

I agree that having a newline at the end is nice, but a lack or excess of them causes no issues.
