### ISSUE TITLE
BackpackScript:1066: attempt to call method 'Select' (a nil value) 

### ISSUE THREAD

**Issue by TheSneak** [Roblox/Core-Scripts#163]
`CoreGui.RobloxGui.Modules.BackpackScript:1066: attempt to call method 'Select' (a nil value)`

This error first appeared May 21 and still occurs. It is triggered by dragging an item from the backpack inventory onto the toolbar.

Stack trace:

```
CoreGui.RobloxGui.Modules.BackpackScript, line 1066 - global changeSlot
CoreGui.RobloxGui.Modules.BackpackScript, line 466
```

**Comment by DeveloperBlue** [comment]
Marked as "Fixing" for May, but it's August and I can still repro the bug.

**Comment by TheSneak** [comment]
Still a problem.  Current stack trace (line number changes):

    CoreGui.RobloxGui.Modules.BackpackScript, line 1011 - global changeSlot
    CoreGui.RobloxGui.Modules.BackpackScript, line 454

**Comment by CodedNil** [comment]
Also getting error, had it for months when dragging things around,
18:35:38.312 - CoreGui.RobloxGui.Modules.BackpackScript:1011: attempt to call method 'Select' (a nil value)
18:35:38.313 - Stack Begin
18:35:38.313 - Script 'CoreGui.RobloxGui.Modules.BackpackScript', Line 1011 - global changeSlot
18:35:38.314 - Script 'CoreGui.RobloxGui.Modules.BackpackScript', Line 454
18:35:38.314 - Stack End

**Comment by TheSneak** [comment]
Still a problem as of 10 Feb 2016. Updated stack trace:

    CoreGui.RobloxGui.Modules.BackpackScript, line 1012 - global changeSlot
    CoreGui.RobloxGui.Modules.BackpackScript, line 455

**Comment by BinaryResolved** [comment]
I have seen this a few times also, I will look into it.

**Comment by BinaryResolved** [comment]
@TheSneak I ain't sure when these get released, but when they do. This issue is fixed.

**Comment by BinaryResolved** [comment]
Fixed.

**Comment by GitBlox** [comment]
This issue was moved to GitBlox/Core-Scripts#7

**Comment by ArceusInator** [comment]
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.
