### ISSUE TITLE
Negative LineHandleAdornment.ZIndex with AlwaysOnTop crashes

### ISSUE THREAD

**Issue by einsteinK** [ROBLOX/Core-Scripts#172]
A rendered LineHandleAdornment will crash studio under those circumstances:
- ZIndex is a negative number (I use -5)
- AlwaysOnTop is set to true
- Adornee is set to a visible part

Not tested with other Adornments or with the camera far from the  adornment.

Works both in studio and client.

**Comment by Anaminus** [comment]
I am able to reproduce this, but only if the ZIndex is less than -2.

**Comment by einsteinK** [comment]
Yeah, I also thought I was on the bug tracker...
Time to move.
