### ISSUE TITLE
Error in PurchasePromptScript

### ISSUE THREAD

**Issue by Anaminus** [ROBLOX/Core-Scripts#18]
*See [original issue](https://github.com/Anaminus/roblox-bug-tracker/issues/306) by @TheSneak*

----

I am seeing this error in Google Analytics using the new GA module:

    CoreGui.RobloxGui.CoreScripts/PurchasePromptScript:665: attempt to index upvalue 'currentProductInfo' (a nil value) | CoreGui.RobloxGui.CoreScripts/PurchasePromptScript, line 665 - global canPurchaseItem CoreGui.RobloxGui.CoreScripts/PurchasePromptScript, line 180

**Comment by jmargh** [comment]
Closing as new purchase script is live.
