### ISSUE TITLE
When teleporting from studio, dialog does not respect CustomizedTeleportUI

### ISSUE THREAD

**Issue by Anaminus** [Roblox/Core-Scripts#19]
_See [original issue](https://github.com/Anaminus/roblox-bug-tracker/issues/279) by @Anaminus_

---

Currently, when you attempt to teleport from the studio, a dialog pops up indicating that you can't do that. This dialog is displayed even when [TeleportService.CustomizedTeleportUI](http://anaminus.github.io/api/class/TeleportService.html#memberCustomizedTeleportUI) is true.

**Comment by BinaryResolved** [comment]
@Anaminus Is this still occurring?

**Comment by slixxed** [comment]
This issue was moved to slixxed/Core-Scripts#1

**Comment by slixxed** [comment]
This issue was moved to slixxed/Core-Scripts#2

**Comment by GitBlox** [comment]
This issue was moved to GitBlox/Core-Scripts#1

**Comment by ArceusInator** [comment]
The ISsue IS MY doodDoo Hawl IS Malwdy

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.
