### ISSUE TITLE
ROBLOX's scripts output "attempt to call a nil value"

### ISSUE THREAD

**Issue by Anaminus** [Roblox/Core-Scripts#20]
_see [original issue](https://github.com/Anaminus/roblox-bug-tracker/issues/212) by @Quenty_

---

One of ROBLOX's core scripts will output "attempt to call a nil value" in solo test mode If certain conditions are met.

It appears when you load a character, and you have set the Players.ChracterAutoloads to false, then you will break some unknown script.
## Repro

1) Make a new place in studio
2) Set Players.CharacterAutoLoads to false
3) Test in SoloTestMode or the new Character Play Mode
4) Run this code whenever you want, in that test mode.

> game.Players.Player1:LoadCharacter() 

![image](https://f.cloud.github.com/assets/1774409/2115001/c3312084-9046-11e3-8c0e-e5d3e3af9e6e.png)

Tadah. Error.

**Comment by BinaryResolved** [comment]
@Anaminus It seems to be working now. [http://prntscr.com/atykp6](url)

**Comment by GitBlox** [comment]
This issue was moved to GitBlox/Core-Scripts#2

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by ArceusInator** [comment]
NIGAR Fawk MY Buthole : (

**Comment by cliffchapmanrbx** [comment]
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.
