### ISSUE TITLE
Usage | TenFootInterface

### ISSUE THREAD

**Issue by Darnus** [ROBLOX/Core-Scripts#203]
Upon looking through the code of the PromptPurchaseScript2:

https://github.com/ROBLOX/Core-Scripts/blob/master/CoreScriptsRoot/CoreScripts/PurchasePromptScript2.lua

I realized that it required a module script by the name of the TenFootInterface. When I looked through Roblox's modules, I found it:

https://github.com/ROBLOX/Core-Scripts/blob/master/CoreScriptsRoot/Modules/TenFootInterface.lua

However, when I plugged the two scripts together, I received an issue. 

In the PromptPurchaseScript2:

```
local TenFootInterface = require(RobloxGui.Modules.TenFootInterface)
```

```
13:02:32.266 - Requested module experienced an error while loading
```

In the TenFootInterface:

```
local CoreGui = game:GetService("CoreGui")
local RobloxGui = CoreGui:WaitForChild("RobloxGui") 
```
```
13:02:32.268 - An error occurred
```
I believe the issue is that you cannot access the CoreGui > RobloxGui without using a CoreScript, which normal users do not have access to. I am not certain this is the issue, but it is my best guess. Is there a way I can use Roblox's PromptPurchaseScript for my own purposes, to provide an ingame purchasing gui, for my own currency? I have seen multiple people achieve this, but I do not understand how they do it.

**Comment by einsteinK** [comment]
The PromptPurchaseScript uses a lot of (protected) HTTP stuff.
You're maybe better off writing a totally new script, while looking here now and then for ideas.

**Comment by Darnus** [comment]
Yes, I realized that when talking to jmargh. I pretty much have a solid idea how to replicate it for my own use now. Thanks though!
