### ISSUE TITLE
Library failed to load | CoreGui.RobloxGui.CoreScripts/DeveloperConsole, line 4

### ISSUE THREAD

**Issue by TheSneak** [ROBLOX/Core-Scripts#22]
CoreGui.RobloxGui.CoreScripts/DeveloperConsole:4: Library failed to load | CoreGui.RobloxGui.CoreScripts/DeveloperConsole, line 4

**Comment by BinaryResolved** [comment]
@TheSneak Is this still happening?

**Comment by TheSneak** [comment]
No. Last time I saw this was August 2014

**Comment by BinaryResolved** [comment]
Mind closing it then?

-----Original Message-----
