### ISSUE TITLE
Library failed to load | CoreGui.RobloxGui.CoreScripts/Settings, line 16

### ISSUE THREAD

**Issue by TheSneak** [ROBLOX/Core-Scripts#23]
Perhaps related to #22 

    CoreGui.RobloxGui.CoreScripts/Settings:16: Library failed to load | CoreGui.RobloxGui.CoreScripts/Settings, line 16

**Comment by BinaryResolved** [comment]
Is this one still occurring?@TheSneak

**Comment by TheSneak** [comment]
No longer an issue. Closing.
