### ISSUE TITLE
MarketplaceService:getProductInfo() failed because

### ISSUE THREAD

**Issue by TheSneak** [ROBLOX/Core-Scripts#24]
MarketplaceService:getProductInfo() failed because https://api.roblox.com/marketplace/productinfo?assetId=117931593: HttpSendRequest, err=0x2EE7

**Comment by jmargh** [comment]
I know this is an old issue, but did this occur in the old purchase script? (LoadingScript was not enabled at this time)

The error is the result of the API call making a web call that failed. All current CoreScripts that call this pcall the call, so scripts should not be crashing.

Will leave open for a bit but if this doesn't come up anymore I will close the issue. Thanks!

**Comment by TheSneak** [comment]
I am still seeing similar errors, though the error varies. Each of these errors was seen within the past week:

    MarketplaceService:getProductInfo() failed because https://api.roblox.com/marketplace/productinfo?assetId=<PlaceId>: HttpSendRequest, err=0x2EE2
    MarketplaceService:getProductInfo() failed because HTTP -1001
    MarketplaceService:getProductInfo() failed because rawProductInfo was empty
    MarketplaceService:getProductInfo() failed because https://api.roblox.com/marketplace/productinfo?assetId=<AudioTrackId>: WinHttpReceiveResponse, err=0x2EFE

**Comment by jmargh** [comment]
This will be handled better from this 54a62974dd84c56eb5ed5cc9ac842e1b6582a1a5

Those errors are engine level errors. The web call is failing or it's getting back empty JSON.

**Comment by TheSneak** [comment]
Last seen on 11/21/2015. Closing.
