### ISSUE TITLE
Whispers broken for those with a _ on their username

### ISSUE THREAD

**Issue by RafDevRBLX** [ROBLOX/Core-Scripts#327]
On lines 936-937 of the Chat CoreScript, you can't whisper to people with underscores on their name.
Possible fix would be changing `(%w+)` to `(%w+_?%w+)`

**Comment by matthewdean** [comment]
I think ```[%w_]+``` is more suitable. There is no need to enforce the website's business logic on usernames in the client.

**Comment by ConorGriffin37** [comment]
This was closed by #335
