### ISSUE TITLE
Question about some GuiService methods that are currently undocumented?

### ISSUE THREAD

**Issue by CloneTrooper1019** [Roblox/Core-Scripts#338]
There are three methods under the GuiService that are currently undocumented.
I see them being used in this repository, but I still can't figure out what their exact purpose is, despite some attempted testing.

The methods in question:

GuiService:AddSelectionParent(string selectionName, GuiObject selectionParent)
GuiService:AddSelectionTuple(string selectionName, Tuple<GuiObject> selections)
GuiService:RemoveSelectionGroup(string selectionName)

What are they used for? Are they of any use to developers?
Any information would be helpful.
Thanks ;)

@hockeychaos @SolarCrane

**Comment by jmargh** [comment]
I'll jump in.

AddSelectionParent - Creates a gui selection group where gamepad gui navigation will only consider selectable gui objects that are within the group (children of selectionParent). A use case is you have a menu pop open, but there are other selectable objects on the screen (maybe from previous menus), but you want to the user to only be able to select gui objects in the new menu.

AddSelectionTuple - similar to AddSelectionParent, but you can give it a tuple of gui objects you want to be contained in the group.

RemoveSelectionGroup - Removes a group that was created with AddSelectionParent or AddSelectionTuple.

Part of the gamepad gui navigate logic considers selection groups if there are any, when trying to determine what the next selection should be when navigating. So these give you control over what you want the user to be able to navigate to.

**Comment by CloneTrooper1019** [comment]
Alright cool!
So does this mean only one group can be active at a time? If so, what's the purpose of selectionName?

**Comment by GitBlox** [comment]
This issue was moved to GitBlox/Core-Scripts#17
