### ISSUE TITLE
CreateChatLineRender Errors in Bubble Chat

### ISSUE THREAD

**Issue by TheNickmaster21** [ROBLOX/Core-Scripts#379]
CoreGui.RobloxGui.CoreScripts/BubbleChat:529: attempt to index local 'billboardGui' (a nil value) | CoreGui.RobloxGui.CoreScripts/BubbleChat, line 529 - method CreateChatLineRender CoreGui.RobloxGui.CoreScripts/BubbleChat, line 599 - method OnPlayerChatMessage CoreGui.RobloxGui.CoreScripts/BubbleChat, line 633

**Comment by BinaryResolved** [comment]
@TheNickmaster21 Have any reproduction steps?

**Comment by GitBlox** [comment]
This issue was moved to GitBlox/Core-Scripts#20

**Comment by TheNickmaster21** [comment]
I get this constantly in Farming among Friends: https://i.imgur.com/3Uc9BNa.png
