### ISSUE TITLE
Backpack error

### ISSUE THREAD

**Issue by Partixel** [ROBLOX/Core-Scripts#392]
CoreGui.RobloxGui.Modules.BackpackScript:1012: attempt to call method 'Select' (a nil value) | CoreGui.RobloxGui.Modules.BackpackScript, line 1012 - global changeSlot CoreGui.RobloxGui.Modules.BackpackScript, line 455

**Comment by BinaryResolved** [comment]
@Partixel We already have a issue for this bug. However the bug is technically fixed, next time the core-scripts from here get released it will no longer have this issue. Reference to the original issue: https://github.com/ROBLOX/Core-Scripts/issues/163

**Comment by BinaryResolved** [comment]
@Partixel Thanks man, if you have any other bugs regarding the core scripts. Don't hesitate to post here. :)
