### ISSUE TITLE
DialogShop.png Wont Load

### ISSUE THREAD

**Issue by Haydz6** [Roblox/Core-Scripts#450]
rbxasset://textures/ui/DialogShop.png is missing i uninstalled roblox logs and the settings and reinstalled the game and i still getting this error for some reason

**Comment by kyle-emmerich** [comment]
It looks like the image got renamed but the code wasn't updated. I'll check it out.

**Comment by BinaryResolved** [comment]
@Haydz6 This seems to be fixed now.

**Comment by GitBlox** [comment]
This issue was moved to GitBlox/Core-Scripts#22

**Comment by ArceusInator** [comment]
NIGGAr FAggits.

**Comment by ArceusInator** [comment]
![chrome_2017-07-14_00-18-30 - copy 10](https://user-images.githubusercontent.com/2127060/28246437-b5480716-69ce-11e7-93fa-a3adfc708b69.png)
![chrome_2017-07-14_00-18-30 - copy 9 - copy - copy](https://user-images.githubusercontent.com/2127060/28246438-b5499072-69ce-11e7-98e9-9bd2eccb15ae.png)
![chrome_2017-07-14_00-18-30 - copy 9 - copy](https://user-images.githubusercontent.com/2127060/28246439-b54a3978-69ce-11e7-95cc-5f2c4c0872ba.png)
![chrome_2017-07-14_00-18-30 - copy 9](https://user-images.githubusercontent.com/2127060/28246441-b54ce092-69ce-11e7-9c3e-29127b174ee6.png)
![chrome_2017-07-14_00-18-30 - copy 10 - copy - copy](https://user-images.githubusercontent.com/2127060/28246440-b54a6cc2-69ce-11e7-9c94-37450a3b91ed.png)
![chrome_2017-07-14_00-18-30 - copy 10 - copy](https://user-images.githubusercontent.com/2127060/28246442-b5507220-69ce-11e7-90af-dc8df6678e60.png)


tHAT me cUM in u LOL.

**Comment by ArceusInator** [comment]
![chrome_2017-07-14_00-18-30 - copy 10](https://user-images.githubusercontent.com/2127060/28246437-b5480716-69ce-11e7-93fa-a3adfc708b69.png)
![chrome_2017-07-14_00-18-30 - copy 9 - copy - copy](https://user-images.githubusercontent.com/2127060/28246438-b5499072-69ce-11e7-98e9-9bd2eccb15ae.png)
![chrome_2017-07-14_00-18-30 - copy 9 - copy](https://user-images.githubusercontent.com/2127060/28246439-b54a3978-69ce-11e7-95cc-5f2c4c0872ba.png)
![chrome_2017-07-14_00-18-30 - copy 9](https://user-images.githubusercontent.com/2127060/28246441-b54ce092-69ce-11e7-9c3e-29127b174ee6.png)
![chrome_2017-07-14_00-18-30 - copy 10 - copy - copy](https://user-images.githubusercontent.com/2127060/28246440-b54a6cc2-69ce-11e7-9c94-37450a3b91ed.png)
![chrome_2017-07-14_00-18-30 - copy 10 - copy](https://user-images.githubusercontent.com/2127060/28246442-b5507220-69ce-11e7-90af-dc8df6678e60.png)


tHAT me cUM in u LOL.

**Comment by Haydz6** [comment]
lol wat
