### ISSUE TITLE
Infinite yield possible on 'RobloxReplicatedStorage:WaitForChild("SetDialogInUse")' 

### ISSUE THREAD

**Issue by JetCrusherTorpedo** [ROBLOX/Core-Scripts#468]
22:19:10.068 - Infinite yield possible on 'RobloxReplicatedStorage:WaitForChild("SetDialogInUse")'
22:19:10.070 - Stack Begin
22:19:10.070 - Script 'CoreGui.RobloxGui.CoreScripts/MainBotChatScript2', Line 71
22:19:10.070 - Stack End

**Comment by PhoenixShay** [comment]
this is a problem with WaitForChild, not the corescripts themselves

someone at ROBLOX probably tried to make some sort of loop prevention on WaitForChild but never finished it

**Comment by kyle-emmerich** [comment]
No, this is intended behavior. We knew that this sort of thing would show up going into this. You can safely ignore it.

What's happening is that the script uses WaitForChild to yield itself until SetDialogInUse is added to RobloxReplicatedStorage. This usage accounts for a very tiny proportion of what you'd usually use WFC for, so we provided that warning to make the normal usage easier.
