### ISSUE TITLE
Dialog object does not reset after activation

### ISSUE THREAD

**Issue by LucasWolschick** [ROBLOX/Core-Scripts#546]
After using a Dialog, you can never use it again (prompt bubble never shows up after dialog conclusion).

Steps to reproduce:
1. Create/visit any place which has a dialog
2. Use the dialog, end it in any point ("Goodbye!", or reaching the end)
3. Notice how the prompt bubble never shows up again.

**Comment by HuddaFire** [comment]
Prompt bubble will appear after a long while.

However, this is still an issue that I want fixed.

**Comment by LucasWolschick** [comment]
No, really, the prompt bubble won't show up again

**Comment by LucasWolschick** [comment]
Any thoughts on this?

**Comment by Quenty** [comment]
This occurs only when FilteringEnable is turned on, and is due to a big where the property doesn't replicate back to the server. The legacy code spawned in a script, but in the case of FilteringEnabled, this is not viable.

**Comment by LucasWolschick** [comment]
@Quenty, I've already tested it in several non-filteringenabled games as well as filteringenabled ones, and I can say the same bug happens in all cases.

**Comment by HuddaFire** [comment]
Tested with Test Server in studio, for me the bug occurs in both FE and
non-FE. I'm going to be looking around for cases where the prompt does pop
up again, it's hard though.

**Comment by LucasWolschick** [comment]
I can't seem to find any scenario that the prompt appears again.

**Comment by BinaryResolved** [comment]
I can't replicate this, the prompt bubble reappears for me.

**Comment by DarraghGriffin** [comment]
I think this is fixed by #566

**Comment by GitBlox** [comment]
This issue was moved to GitBlox/Core-Scripts#26

**Comment by LucasWolschick** [comment]
I can't replicate this anymore too, guessing it was fixed.
