### ISSUE TITLE
Dialogs not resetting after use 

### ISSUE THREAD

**Issue by foreverpower** [ROBLOX/Core-Scripts#624]
Reopening this because the last fix only solved this problem in Studio, not in game.

Reproduction steps:

1. Create/visit any place which has a dialog (on Roblox, not in studio)
2. Use the dialog, end it in any point ("Goodbye!", or reaching the end)
3. Notice how the prompt bubble never shows up again.

There also seems to be another related bug where dialogs do not time out if you do not respond in time (as they are supposed to).

**Comment by foreverpower** [comment]
It seems like this is related to #442. It seems like a RemoteEvent is being created by the client in addition to the server, and the client hooks to and invokes the wrong event. I will see if ServerSocialScript is also being affected by this.

**Comment by foreverpower** [comment]
Alright, confirmed that ServerSocialScript is affected. See my post on 442 for complete explanation.

**Comment by DarraghGriffin** [comment]
The Server CoreScripts issue has been fixed, can you verify that this fixes the dialog issue?

**Comment by foreverpower** [comment]
This seems to have fixed it. Closing.
