### ISSUE TITLE
Mute button in the PlayerList no longer works.

### ISSUE THREAD

**Issue by DarraghGriffin** [ROBLOX/Core-Scripts#657]
There is currently a drop down player list menu which allows users to mute other users, since the introduction of the new chat this no longer works because the new chat and the playerlist don't share modules anymore.

@ConorGriffin37 should fix this, we will need to add a SetCore method to share the list of muted users between the player list and the chat.

**Comment by ConorGriffin37** [comment]
This has been fixed.

**Comment by DarraghGriffin** [comment]
Thanks
