### ISSUE TITLE
Players:Chat errors

### ISSUE THREAD

**Issue by foreverpower** [ROBLOX/Core-Scripts#665]
Players:Chat (as used by the new chat) generates the following errors:

1. On the server in studio: 
"WebChat failed with reason(WebChatFilter FilterMessageWithCallbackResponseHandlerLockAcquiredHandleResponse http post exception(HTTP 0 (HTTP 403 (HTTP/1.1 403 Forbidden))))"

2. On an online game when playing as a guest:
"SuperSafe chat is on"

**Comment by ConorGriffin37** [comment]
I submitted a fix for the error in studio. I don't think this method should be called on a guest online, as guests are not allowed to chat.
