### ISSUE TITLE
Add an "EmotesEnabled" CoreGui option

### ISSUE THREAD

**Issue by boynedmaster** [ROBLOX/Core-Scripts#748]
Right now to disable emotes you need to completely overwrite Animate.

There are many valid reasons to want to disable emotes, including realism in a game.

I believe disabling emotes should be simplified to a CoreGui option.

    game:GetService("StarterGui"):SetCore("EmotesEnabled", false) --disables emotes
    game:GetService("StarterGui"):SetCore("EmotesEnabled", true) --reenables emotes

**Comment by boynedmaster** [comment]
There is a way to disable emotes that I had forgotten, modifying ChatServiceRunner to remove these lines.

	elseif (string.sub(message, 1, 3) == "/e " or string.sub(message, 1, 7) == "/emote ") then
		-- Just don't show these in the chatlog. The animation script listens on these.
		return true

I will close this topic now.

**Comment by foreverpower** [comment]
Removing those lines won't stop emotes, it will just unhide emote messages in chat. But all you need to do is override the animation script and remove the part of the script that listens for chat commands, although I guess a SetCore could be useful for forward compatibility.

**Comment by boynedmaster** [comment]
Really? I'll reopen this then.

**Comment by boynedmaster** [comment]
Actually, I'll close this again (lol) because Animate isn't a CoreScript.

**Comment by RobloxCodeWriter** [comment]
We'll be making this easier to do without having to overwrite the Animate script in the future.
