### ISSUE TITLE
Back Easing Style Jumpy w/ InOut Direction

### ISSUE THREAD

**Issue by ClockworkSquirrel** [Roblox/Core-Scripts#826]
**Description**
The `Enum.EasingStyle.Back` easing style results in jumpy/jittery movement at the start of the tween when using in conjunction with `Enum.EasingDirection.InOut` on the `GuiObject::TweenPosition` method.

**Media**
<details><summary>Click to Expand</summary>

![](https://cloud.githubusercontent.com/assets/21029087/25006932/a389d4bc-2056-11e7-9715-003b7c8a86f7.gif)
</details>

**Comment by ArceusInator** [comment]
IN Out UR bawTHOle LOL

![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)
![dlzapoo](http://cdn4.images.motherlessmedia.com/images/3F3D51C.jpg?fs=opencloud)

**Comment by ClockworkSquirrel** [comment]
as much as I wouldn't mind that in my bawthole, I don't think that solves our problem with the tweening
