### ISSUE TITLE
CoreGui.RobloxGui.CoreScripts/ChatScript2:1628: attempt to compare number with nil

### ISSUE THREAD

**Issue by TheSneak** [ROBLOX/Core-Scripts#97]
CoreGui.RobloxGui.CoreScripts/ChatScript2:1628: attempt to compare number with nil 

Stack trace:

    CoreGui.RobloxGui.CoreScripts/ChatScript2, line 1628

**Comment by einsteinK** [comment]
Seems to me to be an internal error (after reviewing the code)
InputObjects are known for being... buggy.

(I think it's internally trying to compare number with nil, maybe even using ==, erroring in C)
(Just guessing with that part, but in the code itself only == is used)

**Comment by SolarCrane** [comment]
Fixed in 4ddd6a193100299ba1cf84f34227da4297fdf823
